//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdornos.Caja.UI.IntegracionReferencia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cache_tblProducto", Namespace="http://autoadornos.com/")]
    [System.SerializableAttribute()]
    public partial class Cache_tblProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private System.Nullable<decimal> PrecioField;
        
        private System.Nullable<int> ExistenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> Existencia {
            get {
                return this.ExistenciaField;
            }
            set {
                if ((this.ExistenciaField.Equals(value) != true)) {
                    this.ExistenciaField = value;
                    this.RaisePropertyChanged("Existencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemVenta", Namespace="http://autoadornos.com/")]
    [System.SerializableAttribute()]
    public partial class ItemVenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> IdProductoField;
        
        private System.Nullable<int> IdServicioField;
        
        private int CantidadField;
        
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> IdServicio {
            get {
                return this.IdServicioField;
            }
            set {
                if ((this.IdServicioField.Equals(value) != true)) {
                    this.IdServicioField = value;
                    this.RaisePropertyChanged("IdServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://autoadornos.com/", ConfigurationName="IntegracionReferencia.IntegracionServiceSoap")]
    public interface IntegracionServiceSoap {
        
        // CODEGEN: Generating message contract since element name ListarProductosResult from namespace http://autoadornos.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://autoadornos.com/ListarProductos", ReplyAction="*")]
        AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosResponse ListarProductos(AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autoadornos.com/ListarProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosResponse> ListarProductosAsync(AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://autoadornos.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://autoadornos.com/ValidarUsuario", ReplyAction="*")]
        AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioResponse ValidarUsuario(AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autoadornos.com/ValidarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioResponse> ValidarUsuarioAsync(AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name canalVenta from namespace http://autoadornos.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://autoadornos.com/RegistrarVenta", ReplyAction="*")]
        AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaResponse RegistrarVenta(AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autoadornos.com/RegistrarVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaResponse> RegistrarVentaAsync(AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequest request);
        
        // CODEGEN: Generating message contract since element name SincronizarVentasOfflineResult from namespace http://autoadornos.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://autoadornos.com/SincronizarVentasOffline", ReplyAction="*")]
        AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineResponse SincronizarVentasOffline(AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autoadornos.com/SincronizarVentasOffline", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineResponse> SincronizarVentasOfflineAsync(AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarProductos", Namespace="http://autoadornos.com/", Order=0)]
        public AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequestBody Body;
        
        public ListarProductosRequest() {
        }
        
        public ListarProductosRequest(AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarProductosRequestBody {
        
        public ListarProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarProductosResponse", Namespace="http://autoadornos.com/", Order=0)]
        public AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosResponseBody Body;
        
        public ListarProductosResponse() {
        }
        
        public ListarProductosResponse(AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://autoadornos.com/")]
    public partial class ListarProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoAdornos.Caja.UI.IntegracionReferencia.Cache_tblProducto[] ListarProductosResult;
        
        public ListarProductosResponseBody() {
        }
        
        public ListarProductosResponseBody(AutoAdornos.Caja.UI.IntegracionReferencia.Cache_tblProducto[] ListarProductosResult) {
            this.ListarProductosResult = ListarProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarUsuario", Namespace="http://autoadornos.com/", Order=0)]
        public AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequestBody Body;
        
        public ValidarUsuarioRequest() {
        }
        
        public ValidarUsuarioRequest(AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://autoadornos.com/")]
    public partial class ValidarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public ValidarUsuarioRequestBody() {
        }
        
        public ValidarUsuarioRequestBody(string usuario, string clave) {
            this.usuario = usuario;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarUsuarioResponse", Namespace="http://autoadornos.com/", Order=0)]
        public AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioResponseBody Body;
        
        public ValidarUsuarioResponse() {
        }
        
        public ValidarUsuarioResponse(AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://autoadornos.com/")]
    public partial class ValidarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidarUsuarioResult;
        
        public ValidarUsuarioResponseBody() {
        }
        
        public ValidarUsuarioResponseBody(bool ValidarUsuarioResult) {
            this.ValidarUsuarioResult = ValidarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarVenta", Namespace="http://autoadornos.com/", Order=0)]
        public AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequestBody Body;
        
        public RegistrarVentaRequest() {
        }
        
        public RegistrarVentaRequest(AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://autoadornos.com/")]
    public partial class RegistrarVentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idVehiculo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idSucursal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string canalVenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AutoAdornos.Caja.UI.IntegracionReferencia.ItemVenta[] detalles;
        
        public RegistrarVentaRequestBody() {
        }
        
        public RegistrarVentaRequestBody(int idCliente, int idVehiculo, int idUsuario, int idSucursal, string canalVenta, decimal total, AutoAdornos.Caja.UI.IntegracionReferencia.ItemVenta[] detalles) {
            this.idCliente = idCliente;
            this.idVehiculo = idVehiculo;
            this.idUsuario = idUsuario;
            this.idSucursal = idSucursal;
            this.canalVenta = canalVenta;
            this.total = total;
            this.detalles = detalles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarVentaResponse", Namespace="http://autoadornos.com/", Order=0)]
        public AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaResponseBody Body;
        
        public RegistrarVentaResponse() {
        }
        
        public RegistrarVentaResponse(AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://autoadornos.com/")]
    public partial class RegistrarVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistrarVentaResult;
        
        public RegistrarVentaResponseBody() {
        }
        
        public RegistrarVentaResponseBody(string RegistrarVentaResult) {
            this.RegistrarVentaResult = RegistrarVentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SincronizarVentasOfflineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SincronizarVentasOffline", Namespace="http://autoadornos.com/", Order=0)]
        public AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequestBody Body;
        
        public SincronizarVentasOfflineRequest() {
        }
        
        public SincronizarVentasOfflineRequest(AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SincronizarVentasOfflineRequestBody {
        
        public SincronizarVentasOfflineRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SincronizarVentasOfflineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SincronizarVentasOfflineResponse", Namespace="http://autoadornos.com/", Order=0)]
        public AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineResponseBody Body;
        
        public SincronizarVentasOfflineResponse() {
        }
        
        public SincronizarVentasOfflineResponse(AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://autoadornos.com/")]
    public partial class SincronizarVentasOfflineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SincronizarVentasOfflineResult;
        
        public SincronizarVentasOfflineResponseBody() {
        }
        
        public SincronizarVentasOfflineResponseBody(string SincronizarVentasOfflineResult) {
            this.SincronizarVentasOfflineResult = SincronizarVentasOfflineResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegracionServiceSoapChannel : AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegracionServiceSoapClient : System.ServiceModel.ClientBase<AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap>, AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap {
        
        public IntegracionServiceSoapClient() {
        }
        
        public IntegracionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegracionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosResponse AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap.ListarProductos(AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequest request) {
            return base.Channel.ListarProductos(request);
        }
        
        public AutoAdornos.Caja.UI.IntegracionReferencia.Cache_tblProducto[] ListarProductos() {
            AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequest inValue = new AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequest();
            inValue.Body = new AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequestBody();
            AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosResponse retVal = ((AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap)(this)).ListarProductos(inValue);
            return retVal.Body.ListarProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosResponse> AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap.ListarProductosAsync(AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequest request) {
            return base.Channel.ListarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosResponse> ListarProductosAsync() {
            AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequest inValue = new AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequest();
            inValue.Body = new AutoAdornos.Caja.UI.IntegracionReferencia.ListarProductosRequestBody();
            return ((AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap)(this)).ListarProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioResponse AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap.ValidarUsuario(AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuario(request);
        }
        
        public bool ValidarUsuario(string usuario, string clave) {
            AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequest inValue = new AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequest();
            inValue.Body = new AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioResponse retVal = ((AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap)(this)).ValidarUsuario(inValue);
            return retVal.Body.ValidarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioResponse> AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap.ValidarUsuarioAsync(AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioResponse> ValidarUsuarioAsync(string usuario, string clave) {
            AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequest inValue = new AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequest();
            inValue.Body = new AutoAdornos.Caja.UI.IntegracionReferencia.ValidarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            return ((AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap)(this)).ValidarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaResponse AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap.RegistrarVenta(AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequest request) {
            return base.Channel.RegistrarVenta(request);
        }
        
        public string RegistrarVenta(int idCliente, int idVehiculo, int idUsuario, int idSucursal, string canalVenta, decimal total, AutoAdornos.Caja.UI.IntegracionReferencia.ItemVenta[] detalles) {
            AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequest inValue = new AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequest();
            inValue.Body = new AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.idVehiculo = idVehiculo;
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.idSucursal = idSucursal;
            inValue.Body.canalVenta = canalVenta;
            inValue.Body.total = total;
            inValue.Body.detalles = detalles;
            AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaResponse retVal = ((AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap)(this)).RegistrarVenta(inValue);
            return retVal.Body.RegistrarVentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaResponse> AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap.RegistrarVentaAsync(AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequest request) {
            return base.Channel.RegistrarVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaResponse> RegistrarVentaAsync(int idCliente, int idVehiculo, int idUsuario, int idSucursal, string canalVenta, decimal total, AutoAdornos.Caja.UI.IntegracionReferencia.ItemVenta[] detalles) {
            AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequest inValue = new AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequest();
            inValue.Body = new AutoAdornos.Caja.UI.IntegracionReferencia.RegistrarVentaRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.idVehiculo = idVehiculo;
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.idSucursal = idSucursal;
            inValue.Body.canalVenta = canalVenta;
            inValue.Body.total = total;
            inValue.Body.detalles = detalles;
            return ((AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap)(this)).RegistrarVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineResponse AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap.SincronizarVentasOffline(AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequest request) {
            return base.Channel.SincronizarVentasOffline(request);
        }
        
        public string SincronizarVentasOffline() {
            AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequest inValue = new AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequest();
            inValue.Body = new AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequestBody();
            AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineResponse retVal = ((AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap)(this)).SincronizarVentasOffline(inValue);
            return retVal.Body.SincronizarVentasOfflineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineResponse> AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap.SincronizarVentasOfflineAsync(AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequest request) {
            return base.Channel.SincronizarVentasOfflineAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineResponse> SincronizarVentasOfflineAsync() {
            AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequest inValue = new AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequest();
            inValue.Body = new AutoAdornos.Caja.UI.IntegracionReferencia.SincronizarVentasOfflineRequestBody();
            return ((AutoAdornos.Caja.UI.IntegracionReferencia.IntegracionServiceSoap)(this)).SincronizarVentasOfflineAsync(inValue);
        }
    }
}
