//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdornos.Caja.UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoAdornos_CajaLocalEntities : DbContext
    {
        public AutoAdornos_CajaLocalEntities()
            : base("name=AutoAdornos_CajaLocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblFacturaDetalleLocal> tblFacturaDetalleLocals { get; set; }
        public virtual DbSet<tblFacturaLocal> tblFacturaLocals { get; set; }
        public virtual DbSet<tblProductoCache> tblProductoCaches { get; set; }
    }
}
