//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdornos.Caja.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFacturaDetalleLocal
    {
        public int IdDetalle { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
    
        public virtual tblFacturaLocal tblFacturaLocal { get; set; }
    }
}
