//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdornos.Caja.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFacturaLocal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFacturaLocal()
        {
            this.tblFacturaDetalleLocals = new HashSet<tblFacturaDetalleLocal>();
        }
    
        public int IdFactura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CedulaCliente { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> EnviadoAIntegracion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFacturaDetalleLocal> tblFacturaDetalleLocals { get; set; }
    }
}
