//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integracion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cola_tblFacturaDetalle
    {
        public int IdDetalleLocal { get; set; }
        public Nullable<int> IdFacturaLocal { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Importe { get; set; }
    
        public virtual Cola_tblFactura Cola_tblFactura { get; set; }
    }
}
