//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integracion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cola_tblFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cola_tblFactura()
        {
            this.Cola_tblFacturaDetalle = new HashSet<Cola_tblFacturaDetalle>();
        }
    
        public int IdFacturaLocal { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string CanalVenta { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cola_tblFacturaDetalle> Cola_tblFacturaDetalle { get; set; }
    }
}
