//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integracion.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_IntegracionEntities : DbContext
    {
        public DB_IntegracionEntities()
            : base("name=DB_IntegracionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cache_tblCliente> Cache_tblCliente { get; set; }
        public virtual DbSet<Cache_tblProducto> Cache_tblProducto { get; set; }
        public virtual DbSet<Cache_tblServicio> Cache_tblServicio { get; set; }
        public virtual DbSet<Cola_tblFactura> Cola_tblFactura { get; set; }
        public virtual DbSet<Cola_tblFacturaDetalle> Cola_tblFacturaDetalle { get; set; }
        public virtual DbSet<tblLogServicio> tblLogServicios { get; set; }
    }
}
