//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integracion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogServicio
    {
        public int IdLog { get; set; }
        public string Servicio { get; set; }
        public string Parametros { get; set; }
        public string Respuesta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
