//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdornos.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBAutoAdornosCoreEntities : DbContext
    {
        public DBAutoAdornosCoreEntities()
            : base("name=DBAutoAdornosCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAuditoria> tblAuditorias { get; set; }
        public virtual DbSet<tblCliente> tblClientes { get; set; }
        public virtual DbSet<tblFactura> tblFacturas { get; set; }
        public virtual DbSet<tblFacturaDetalle> tblFacturaDetalles { get; set; }
        public virtual DbSet<tblLogServicio> tblLogServicios { get; set; }
        public virtual DbSet<tblMovimientoInventario> tblMovimientoInventarios { get; set; }
        public virtual DbSet<tblPerfil> tblPerfils { get; set; }
        public virtual DbSet<tblProducto> tblProductoes { get; set; }
        public virtual DbSet<tblServicio> tblServicios { get; set; }
        public virtual DbSet<tblSucursal> tblSucursals { get; set; }
        public virtual DbSet<tblSuplidor> tblSuplidors { get; set; }
        public virtual DbSet<tblUsuario> tblUsuarios { get; set; }
        public virtual DbSet<tblUsuarioPerfil> tblUsuarioPerfils { get; set; }
        public virtual DbSet<tblVehiculo> tblVehiculoes { get; set; }
    
        public virtual ObjectResult<sp_BuscarClientePorCedulaRNC_Result> sp_BuscarClientePorCedulaRNC(string cedulaRNC)
        {
            var cedulaRNCParameter = cedulaRNC != null ?
                new ObjectParameter("CedulaRNC", cedulaRNC) :
                new ObjectParameter("CedulaRNC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarClientePorCedulaRNC_Result>("sp_BuscarClientePorCedulaRNC", cedulaRNCParameter);
        }
    
        public virtual ObjectResult<sp_BuscarClientePorId_Result> sp_BuscarClientePorId(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarClientePorId_Result>("sp_BuscarClientePorId", idClienteParameter);
        }
    
        public virtual ObjectResult<sp_BuscarProductoPorId_Result> sp_BuscarProductoPorId(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarProductoPorId_Result>("sp_BuscarProductoPorId", idProductoParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarFacturaPorId_Result> sp_ConsultarFacturaPorId(Nullable<int> idFactura)
        {
            var idFacturaParameter = idFactura.HasValue ?
                new ObjectParameter("IdFactura", idFactura) :
                new ObjectParameter("IdFactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarFacturaPorId_Result>("sp_ConsultarFacturaPorId", idFacturaParameter);
        }
    
        public virtual int sp_InsertarAuditoria(Nullable<int> idUsuario, string modulo, string accion, string descripcion)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var moduloParameter = modulo != null ?
                new ObjectParameter("Modulo", modulo) :
                new ObjectParameter("Modulo", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarAuditoria", idUsuarioParameter, moduloParameter, accionParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_InsertarCliente(string nombre, string cedulaRNC, string telefono, string direccion, string email, Nullable<bool> esAnonimo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var cedulaRNCParameter = cedulaRNC != null ?
                new ObjectParameter("CedulaRNC", cedulaRNC) :
                new ObjectParameter("CedulaRNC", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var esAnonimoParameter = esAnonimo.HasValue ?
                new ObjectParameter("EsAnonimo", esAnonimo) :
                new ObjectParameter("EsAnonimo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_InsertarCliente", nombreParameter, cedulaRNCParameter, telefonoParameter, direccionParameter, emailParameter, esAnonimoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_InsertarFactura(Nullable<int> idCliente, Nullable<int> idVehiculo, Nullable<int> idUsuario, Nullable<int> idSucursal, string canalVenta, Nullable<decimal> subtotal, Nullable<decimal> impuesto, Nullable<decimal> total)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            var idVehiculoParameter = idVehiculo.HasValue ?
                new ObjectParameter("IdVehiculo", idVehiculo) :
                new ObjectParameter("IdVehiculo", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idSucursalParameter = idSucursal.HasValue ?
                new ObjectParameter("IdSucursal", idSucursal) :
                new ObjectParameter("IdSucursal", typeof(int));
    
            var canalVentaParameter = canalVenta != null ?
                new ObjectParameter("CanalVenta", canalVenta) :
                new ObjectParameter("CanalVenta", typeof(string));
    
            var subtotalParameter = subtotal.HasValue ?
                new ObjectParameter("Subtotal", subtotal) :
                new ObjectParameter("Subtotal", typeof(decimal));
    
            var impuestoParameter = impuesto.HasValue ?
                new ObjectParameter("Impuesto", impuesto) :
                new ObjectParameter("Impuesto", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("Total", total) :
                new ObjectParameter("Total", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_InsertarFactura", idClienteParameter, idVehiculoParameter, idUsuarioParameter, idSucursalParameter, canalVentaParameter, subtotalParameter, impuestoParameter, totalParameter);
        }
    
        public virtual int sp_InsertarFacturaDetalle(Nullable<int> idFactura, Nullable<int> idProducto, Nullable<int> idServicio, Nullable<int> cantidad, Nullable<decimal> precio)
        {
            var idFacturaParameter = idFactura.HasValue ?
                new ObjectParameter("IdFactura", idFactura) :
                new ObjectParameter("IdFactura", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("IdServicio", idServicio) :
                new ObjectParameter("IdServicio", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarFacturaDetalle", idFacturaParameter, idProductoParameter, idServicioParameter, cantidadParameter, precioParameter);
        }
    
        public virtual int sp_InsertarLogServicio(string servicio, string parametros, string respuesta)
        {
            var servicioParameter = servicio != null ?
                new ObjectParameter("Servicio", servicio) :
                new ObjectParameter("Servicio", typeof(string));
    
            var parametrosParameter = parametros != null ?
                new ObjectParameter("Parametros", parametros) :
                new ObjectParameter("Parametros", typeof(string));
    
            var respuestaParameter = respuesta != null ?
                new ObjectParameter("Respuesta", respuesta) :
                new ObjectParameter("Respuesta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarLogServicio", servicioParameter, parametrosParameter, respuestaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_InsertarVehiculo(Nullable<int> idCliente, string marca, string modelo, Nullable<int> anio, string placa, string color)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var modeloParameter = modelo != null ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(string));
    
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var placaParameter = placa != null ?
                new ObjectParameter("Placa", placa) :
                new ObjectParameter("Placa", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("Color", color) :
                new ObjectParameter("Color", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_InsertarVehiculo", idClienteParameter, marcaParameter, modeloParameter, anioParameter, placaParameter, colorParameter);
        }
    
        public virtual ObjectResult<sp_ListarClientes_Result> sp_ListarClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarClientes_Result>("sp_ListarClientes");
        }
    
        public virtual ObjectResult<sp_ListarFacturas_Result> sp_ListarFacturas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarFacturas_Result>("sp_ListarFacturas");
        }
    
        public virtual ObjectResult<sp_ListarProductos_Result> sp_ListarProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarProductos_Result>("sp_ListarProductos");
        }
    
        public virtual ObjectResult<sp_ListarServicios_Result> sp_ListarServicios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarServicios_Result>("sp_ListarServicios");
        }
    
        public virtual ObjectResult<sp_ListarSucursales_Result> sp_ListarSucursales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarSucursales_Result>("sp_ListarSucursales");
        }
    
        public virtual ObjectResult<sp_ListarVehiculosPorCliente_Result> sp_ListarVehiculosPorCliente(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarVehiculosPorCliente_Result>("sp_ListarVehiculosPorCliente", idClienteParameter);
        }
    
        public virtual int sp_RegistrarMovimientoInventario(Nullable<int> idProducto, Nullable<int> idSucursal, string tipoMovimiento, Nullable<int> cantidad, string observacion, Nullable<int> idUsuario)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var idSucursalParameter = idSucursal.HasValue ?
                new ObjectParameter("IdSucursal", idSucursal) :
                new ObjectParameter("IdSucursal", typeof(int));
    
            var tipoMovimientoParameter = tipoMovimiento != null ?
                new ObjectParameter("TipoMovimiento", tipoMovimiento) :
                new ObjectParameter("TipoMovimiento", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarMovimientoInventario", idProductoParameter, idSucursalParameter, tipoMovimientoParameter, cantidadParameter, observacionParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_ValidarUsuario_Result> sp_ValidarUsuario(string nombreUsuario, string clave)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ValidarUsuario_Result>("sp_ValidarUsuario", nombreUsuarioParameter, claveParameter);
        }
    }
}
