//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdornos.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFacturaOfflineRecibida
    {
        public int IdFacturaOfflineRecibida { get; set; }
        public string IdLocal { get; set; }
        public string Cliente { get; set; }
        public decimal Total { get; set; }
        public string Canal { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public string Estado { get; set; }
    }
}
