//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdornos.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFactura()
        {
            this.tblFacturaDetalles = new HashSet<tblFacturaDetalle>();
        }
    
        public int IdFactura { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public int IdUsuario { get; set; }
        public int IdSucursal { get; set; }
        public string CanalVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Impuesto { get; set; }
        public decimal Total { get; set; }
        public string Estado { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual tblSucursal tblSucursal { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblVehiculo tblVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFacturaDetalle> tblFacturaDetalles { get; set; }
    }
}
