//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdornos.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFacturaDetalle
    {
        public int IdFacturaDetalle { get; set; }
        public int IdFactura { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Importe { get; set; }
    
        public virtual tblFactura tblFactura { get; set; }
        public virtual tblProducto tblProducto { get; set; }
        public virtual tblServicio tblServicio { get; set; }
    }
}
