//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdornos.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovimientoInventario
    {
        public int IdMovimientoInventario { get; set; }
        public int IdProducto { get; set; }
        public int IdSucursal { get; set; }
        public string TipoMovimiento { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual tblProducto tblProducto { get; set; }
        public virtual tblSucursal tblSucursal { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
