//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAdornos.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPerfil()
        {
            this.tblUsuarioPerfils = new HashSet<tblUsuarioPerfil>();
        }
    
        public int IdPerfil { get; set; }
        public string NombrePerfil { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsuarioPerfil> tblUsuarioPerfils { get; set; }
    }
}
